--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/life/Personal/Pictures/1610815461919.jpg"

-- Special
background="#0a0a0a"
foreground="#d7d7c7"
cursor="#d7d7c7"

-- Colors
color0="#0a0a0a"
color1="#98AC6E"
color2="#ABCA6C"
color3="#677180"
color4="#558E9D"
color5="#5590A3"
color6="#7CC68B"
color7="#d7d7c7"
color8="#96968b"
color9="#98AC6E"
color10="#ABCA6C"
color11="#677180"
color12="#558E9D"
color13="#5590A3"
color14="#7CC68B"
color15="#d7d7c7"
