# Shell variables
# Generated by 'wal'
wallpaper='/home/life/Personal/Pictures/1610815461919.jpg'

# Special
background='#0a0a0a'
foreground='#d7d7c7'
cursor='#d7d7c7'

# Colors
color0='#0a0a0a'
color1='#98AC6E'
color2='#ABCA6C'
color3='#677180'
color4='#558E9D'
color5='#5590A3'
color6='#7CC68B'
color7='#d7d7c7'
color8='#96968b'
color9='#98AC6E'
color10='#ABCA6C'
color11='#677180'
color12='#558E9D'
color13='#5590A3'
color14='#7CC68B'
color15='#d7d7c7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
